# Generated by Django 3.2.8 on 2022-09-16 05:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('loc', 'LOCAL'), ('ext', 'EXTERNAL')], default='ext', max_length=20)),
                ('type', models.CharField(db_index=True, default='general', max_length=20)),
                ('url', models.URLField(blank=True, max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(db_index=True, max_length=100)),
            ],
            managers=[
                ('ext', django.db.models.manager.Manager()),
            ],
        ),
    ]
