# Generated by Django 3.2.8 on 2022-09-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsobject',
            name='body',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
