# Generated by Django 3.2.8 on 2022-09-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_auto_20220916_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsobject',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
